"""add budgets, savings_goals, debts tables and transaction.debt_id

Revision ID: 397d19bc533d
Revises: ccaf9fda5ed3
Create Date: 2026-07-30 09:30:23.798139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397d19bc533d'
down_revision = 'ccaf9fda5ed3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipe', sa.Enum('hutang', 'piutang', name='debttype'), nullable=False),
    sa.Column('nama_pihak', sa.String(length=100), nullable=False),
    sa.Column('jumlah_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('jumlah_terbayar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jatuh_tempo', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('belum_lunas', 'lunas', name='debtstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_id'), 'debts', ['id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('bulan', sa.Integer(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('jumlah_budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'bulan', 'tahun', name='uq_budget_category_periode')
    )
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_table('savings_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('target_jumlah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_jumlah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('target_tanggal', sa.Date(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_goals_id'), 'savings_goals', ['id'], unique=False)
    op.add_column('transactions', sa.Column('debt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'debts', ['debt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'debt_id')
    op.drop_index(op.f('ix_savings_goals_id'), table_name='savings_goals')
    op.drop_table('savings_goals')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_debts_id'), table_name='debts')
    op.drop_table('debts')
    # ### end Alembic commands ###
